package com.yuyh.sprintnba.http.bean.cookie;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table USER.
 */
public class User implements Serializable {

  public Long id;
  public String userName;
  public String nickName;
  public String uid;
  public String token;
  public String icon;
  public Integer sex;
  public String cookie;
  public String registerTime;
  public String location;
  public String school;
  public String threadUrl;
  public String postUrl;
  public String nickNameUrl;

  public User() {
  }

  public User(Long id) {
    this.id = id;
  }

  public User(Long id, String userName, String uid, String token, String icon, Integer sex,
              String cookie, String registerTime, String location, String school, String threadUrl,
              String postUrl, String nickNameUrl) {
    this.id = id;
    this.userName = userName;
    this.uid = uid;
    this.token = token;
    this.icon = icon;
    this.sex = sex;
    this.cookie = cookie;
    this.registerTime = registerTime;
    this.location = location;
    this.school = school;
    this.threadUrl = threadUrl;
    this.postUrl = postUrl;
    this.nickNameUrl = nickNameUrl;
  }
}
